name: Actions Repository Cleanup

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      manual:
        description: "删除工作流运行"
        type: boolean
        default: true
      commits:
        description: "重置提交历史"
        type: boolean
        default: false

jobs:
  cleanup:
    uses: 3wlh/Actions/.github/workflows/Call_Actions.yml@main
    with:
      auto: ${{ true }}
      manual: ${{ inputs.manual || false }}
      commits: ${{ inputs.commits || false }}
