name: Actions GitHub Pages

on:
  push:
    branches: [main, master]
    
jobs:
  jobs_Actions:
    uses: 3wlh/Actions/.github/workflows/Call_Actions.yml@main
    secrets: inherit
    with:
      commits: true
